### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [vladd-png/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
`The first message was not properly formatted, but most of the following commits were. Try to stick with one pattern/convention. It will help you build good habits. Good job correcting this as you made additional commits.`
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
`Pick a specific type for integer/float.`
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
`Make sure you name your classes singularly, not plurally. I think that this naming actually led to some further confusion about what this class should represent.`
- [ ] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The four methods I chose for **Class #2** represent behaviors or actions.
`The methods and attributes of this class could use a little bit of thought. The class you chose is 'Guest', so we want the methods of this class to be behaviors or actions that a guest would take. Methods like 'order' or 'grabServerAttention' would be better representation of actions that each guest would take. Some of your methods and attributes seem like they would be better scoped to a 'Restaurant' class. For example, a guest probably would not be concerned about the number of seats in the building, but a 'Restaurant' class certainly would. A guest might be concerned about a specific table that they are assigned, but not the entire restaurant's table characteristics. This is important when we build software because it lends itself to the idea of separation of concerns and encapsulation. Does this make sense? I'm happy to elaborate. Just let me know. We'd like you to eliminate the attributes/methods that would not be scoped to the Guest class, and come up with new ones to meet the quota of 4 methods and 4 classes. Make sure you change your object to match these new methods.` 
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message.

`Let us know if you have questions about the feedback above!`

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
Hey @vladd-png , nice work on the updates as I think your Host class makes a lot more sense from an abstraction and encapsulation perspective. There are a couple updates I'd like for your to make:
* [ ] Your waitlist and server_rotation attributes are storing collections, what data type would make more sense for these attributes? Change these attributes to that data type.
* [ ] How does that change affect your methods?
